### ISSUE TITLE
Styles file is not copied with the Report file

### ISSUE THREAD

**Issue by netnic0** [rpii/wdio-html-reporter#78]
Fix:
As the report-styes.css file is not copied each time with the html report.
The css file is fixed into the reporter template.
Could the path of css file be a parameter of the report? this parameter will have a defaut value.
It could the same with the template, to have the possibility to have our own template and styles.

**Comment by rpii** [comment]
This was a feature in the past.  no one was using it so it was removed
during one of the major upgrades.  Will consider it for future update

**Comment by netnic0** [comment]
Thank you for your answer
